### PR TITLE
Update edit dropdowns and fix TS error

### PR DESCRIPTION
**Pull request by SHampton22**
# Description
Update edit form dropdowns and fix a TS error.

Fixes # (issue)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Styling update

# How Has This Been Tested?

- [X] Manual Testing
- [ ] Cypress Testing

# Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] Lint generates no new warnings
- [X] I have checked my terminal and there are no errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all cypress tests are still passing

# Comments for Reviewer(s)

- CORB error still persists.

### CODE REVIEW

**Review by Tristinsorrells1 — COMMENTED** [review]
I see you added "hidden" to the Color and Clothing Type options, what happens when a user edits an item that doesn't have a color or clothing type? Do those drop downs look blank when they are first taken to the edit form? Also, what if an item has a color or type, but the user wants to remove it? Before, selecting the "Color" was the same as removing whatever the current color was (aka setting color to null), how would that work with these edits?

**Review by Tristinsorrells1 — COMMENTED** [review]
Is this an old version of EditItem.tsx? It looks very different from what we have in main?

**Review by pattpjy — APPROVED** [review]

**Review by KarrarQ — APPROVED** [review]
Looks Great ! Good job

**Comment by SHampton22** [comment]
I update the PR to remove the hidden attribute to the color dropdown in AddItem and EditItem as well as adding the All Season option to AddItem. AddItem form and EditItem form now have the same options. This is the current version of EditItem.tsx to the best of my knowledge. If there is concern we can wait and compare in the morning before merging.

**Pull request merged**
