### PR TITLE
Delete

### PR DESCRIPTION
**Pull request by BHaddad1**
# Description

This branch adds delete funcitonality for items in closet, as well as a re-fetch all data once something has been deleted (from closet). 

Fixes # (issue)

#18 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Styling update

# How Has This Been Tested?

- [X] Manual Testing
- [ ] Cypress Testing

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] Lint generates no new warnings
- [x] I have checked my terminal and there are no errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all cypress tests are still passing

# Comments for Reviewer(s)

-

### CODE REVIEW

**Review by Tristinsorrells1 — COMMENTED** [review]
Looks good! Is it necessary to use a union type for id? Are there some instances where id is a number and other's when it is a string?

**Comment by BHaddad1** [comment]
> Looks good! Is it necessary to use a union type for id? Are there some instances where id is a number and other's when it is a string?

It is because of the way it's stored in BE (as a string)

**Comment by Tristinsorrells1** [comment]
When the handleDeleteButton function and the deleteItem function are invoked with id as an argument, is id a number or string?

**Comment by BHaddad1** [comment]
> When the handleDeleteButton function and the deleteItem function are invoked with id as an argument, is id a number or string?

String

**Review by SHampton22 — APPROVED** [review]
Looks great! Thanks!

**Comment by Tristinsorrells1** [comment]
> > When the handleDeleteButton function and the deleteItem function are invoked with id as an argument, is id a number or string?
> 
> 
> 
> String

Got it, could you do id:string if the id parameter will always be a string and the functions shouldn't ever be invoked with id as a number?

**Comment by BHaddad1** [comment]
> > > When the handleDeleteButton function and the deleteItem function are invoked with id as an argument, is id a number or string?
> > 
> > 
> > String
> 
> Got it, could you do id:string if the id parameter will always be a string and the functions shouldn't ever be invoked with id as a number?

Done!

**Pull request merged**
